image: alpine:latest

deploy:
  stage: deploy
  only:
    - master
  script:
    - apk --update add lftp
    - echo "set ftp:ssl-allow no;" >> /tmp/ftpcmd
    - echo "open -u $USER,$PASSWORD -p 20021 h2;" >> /tmp/ftpcmd
    - echo "mirror -Rev ./ ./ --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/" >> /tmp/ftpcmd
    - echo "quit;" >> /tmp/ftpcmd
    - lftp --debug -f /tmp/ftpcmd
    - rm /tmp/ftpcmd

gh-deploy:
  stage: deploy
  only:
    - master
  script:
    - apk --update add git openssh-client
    - mkdir -p ~/.ssh
    - echo "${GH_DEPLOY_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git push -f git@github.com:iotec-gmbh/iotec-gmbh.github.io.git master
