# Welcome to Jekyll!
#

# Site settings
title: iotec GmbH
description: |
    Wir machen Sensoren intelligent
owner: iotec GmbH # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: info@iotec-gmbh.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://new.iotec-gmbh.de" # the base hostname & protocol for your site
social:
  email: info@iotec-gmbh.de
  phone: '+49541-343711-00'
  linkedin-square: https://linkedin.com/company/iotec-gmbh
  github: https://github.com/iotec-gmbh

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Exlude files and directories from the page
exclude:
  # Seems like Jekyll is trying to build what is inside this directory
  - vendor/
  # This is for internal usage only
  - HOWTO.md

about:
  description: |
    iotec ist Ihr Spezialist für individuelle Sensorlösungen. Diese Lösungen befähigen Sie zu belastbaren Analysen Ihrer Prozesse.
    iotec steht Ihnen als starker Partner bei der Transition zu einem digitaleren Unternehmen zur Seite.
    Wir beraten Sie gern und finden mit Ihnen zusammen eine passgenaue Lösung für Ihre Problemstellung.
    Mithilfe unseres Netzwerks aus Industriepartnern und Forschungseinrichtungen unterstützen wir Sie von Machbarkeiten, über Prototypen bis zur Serie.
    Von Temperatursensoren bis zur Integration von Bildverarbeitungssystemen - wir arbeiten immer an der besten digitalen Lösung für Sie.
    Mehr Automatisierung, mehr Digitalisierung, mehr Effizienz für Ihr Unternehmen. Das leistet iotec für Sie.
    In agilen, transparenten Entwicklungsschritten, entwickeln wir für Sie maßgeschneiderte Sensorlösungen.

# References
# To add new references, just copy the image to the images and add a new entry
# in the list below.
references:
  - image: images/boge.svg
    url: https://www.boge-rubber-plastics.com
  - image: images/bayer.svg
    url: https://www.bayer.de
  - image: images/lemken.svg
    url: https://lemken.com
  - image: images/inoex.svg
    url: https://www.inoex.de
  - image: images/hs-osnabrueck.svg
    url: https://www.hs-osnabrueck.de
  - image: images/nietfeld.jpg
    url: http://www.bodenprobetechnik.de

# Services
# *image*: Image next to the text
# *title*: Title of the service
# *description*: Description of the service. Intepreted as Markdown.
services:
  - image: images/consulting.jpg
    title: Beratung
    description: |
        Aliquam ut ex ut augue consectetur interdum.
        Donec hendrerit imperdiet.
        Mauris eleifend fringilla nullam aenean mi ligula.
  - image: images/entwicklung.png
    title: Entwicklung
    description: |
        Aliquam ut ex ut augue consectetur interdum.
        Donec hendrerit imperdiet.
        Mauris eleifend fringilla nullam aenean mi ligula.
  - image: images/forschung.png
    title: Forschung
    description: |
        Aliquam ut ex ut augue consectetur interdum.
        Donec hendrerit imperdiet.
        Mauris eleifend fringilla nullam aenean mi ligula.
