# Welcome to Jekyll!
#

# Site settings
title: iotec GmbH
description: |
    Ihr Parner für den Weg in die Zukunft
owner: iotec GmbH # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: info@iotec-gmbh.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://new.iotec-gmbh.de" # the base hostname & protocol for your site
social:
  email: info@iotec-gmbh.de
  phone: '+49541-343711-00'
  linkedin-square: https://linkedin.com/company/iotec-gmbh
  github: https://github.com/iotec-gmbh

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Exlude files and directories from the page
exclude:
  # Seems like Jekyll is trying to build what is inside this directory
  - vendor/
  # This is for internal usage only
  - HOWTO.md

about:
  description: |
    Die iotec GmbH ist ein etablierter Entwicklungs- und Fertigungsdienstleister im Bereich der Sensorik mit forschungsnaher Hochschulanbindung.
    Das Team setzt sich aus hochqualifizierten, motivierten und erfahrenen Mitarbeitern zusammen.
    Alle Angestellten von iotec haben eine naturwissenschaftliche Ausbildung absolviert (Elektrotechnik, Informatik, Physik, Mathematik, Biologie).
    Das Unternehmen erarbeitet individuelle Lösungen im Bereich der Elektronik und Automatisierungstechnik.
    Hierbei wird der Kunde von der Idee bis zum Serienprodukt begleitet.

# References
# To add new references, just copy the image to the images and add a new entry
# in the list below.
references:
  - image: images/boge.svg
    url: https://www.boge-rubber-plastics.com
  - image: images/bayer.svg
    url: https://www.bayer.de
  - image: images/lemken.svg
    url: https://lemken.com
  - image: images/inoex.svg
    url: https://www.inoex.de
  - image: images/nietfeld.jpg
    url: http://www.bodenprobetechnik.de
