# Welcome to Jekyll!
#

# Site settings
title: iotec GmbH
description: |
    Ihr Parner für den Weg in die Zukunft
owner: iotec GmbH # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: info@iotec-gmbh.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://new.iotec-gmbh.de" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  github: https://github.com/iotec-gmbh
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  email: info@iotec-gmbh.de
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

about:
  description: |
    Die iotec GmbH ist ein etablierter Entwicklungs- und Fertigungsdienstleister im Bereich der Sensorik mit forschungsnaher Hochschulanbindung.
    Das Team setzt sich aus hochqualifizierten, motivierten und erfahrenen Mitarbeitern zusammen.
    Alle Angestellten von iotec haben eine naturwissenschaftliche Ausbildung absolviert (Elektrotechnik, Informatik, Physik, Mathematik, Biologie).
    Das Unternehmen erarbeitet individuelle Lösungen im Bereich der Elektronik und Automatisierungstechnik.
    Hierbei wird der Kunde von der Idee bis zum Serienprodukt begleitet.
