# Welcome to Jekyll!
#

# Site settings
title: iotec GmbH
description: |
    Wir machen Sensoren intelligent
owner: iotec GmbH # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: info@iotec-gmbh.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://new.iotec-gmbh.de" # the base hostname & protocol for your site
social:
  email: info@iotec-gmbh.de
  phone: '+49541-343711-00'
  linkedin-square: https://linkedin.com/company/iotec-gmbh
  github: https://github.com/iotec-gmbh

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Exlude files and directories from the page
exclude:
  # Seems like Jekyll is trying to build what is inside this directory
  - vendor/
  # This is for internal usage only
  - HOWTO.md

about:
  description: |
    iotec ist Ihr Spezialist für individuelle Sensorlösungen. In diesem Bereich bieten wir Ihnen innovative, schnell umgesetzte Prototypen (z.B. MVP) die Sie zu belastbaren Analysen Ihrer Prozesse befähigen.
    Wir beraten Sie gern und finden mit Ihnen zusammen eine passgenaue Lösung für Ihre Problemstellung.
    Mithilfe unseres Netzwerks aus Industriepartnern und Forschungseinrichtungen unterstützen wir Sie von Machbarkeiten, über Prototypen bis zur Serie.
    Von Temperatursensoren bis zur Integration von Bildverarbeitungssystemen - wir arbeiten immer an der besten digitalen Lösung für Sie.

    Mehr Automatisierung, mehr Digitalisierung, mehr Effizienz für Ihr Unternehmen. Das leistet iotec für Sie.
    In kurzen, transparenten Entwicklungsschritten, entwickeln wir für Sie maßgeschneiderte Sensorlösungen.

# References
# To add new references, just copy the image to the images and add a new entry
# in the list below.
references:
  - image: images/bayer.svg
    url: https://www.bayer.de
  - image: images/boge.svg
    url: https://www.boge-rubber-plastics.com
  - image: images/huebner.png
    url: https://www.hubner-group.com/
  - image: images/inoex.svg
    url: https://www.inoex.de
  - image: images/hs-osnabrueck.svg
    url: https://www.hs-osnabrueck.de
  - image: images/luh.svg
    url: https://www.uni-hannover.de
  - image: images/lemken.svg
    url: https://lemken.com
  - image: images/nietfeld.jpg
    url: http://www.bodenprobetechnik.de

# Services
# *image*: Image next to the text
# *title*: Title of the service
# *description*: Description of the service. Intepreted as Markdown.
services:
  - image: images/entwicklung.png
    title: Entwicklung
    description: |
        Wir unterstützten Sie gerne bei der Lösung Ihres Problems.
        Dazu analysieren wir gemeinsam mit Ihnen die aktuelle Situation und erarbeiten spezifische Lösungsansätze auf Basis von Sensoren.
        Diese stellen wir Ihnen in einem Konzept zusammen.
        Aus diesem Konzept können wir die maßgeschneiderte Sensorlösung für Ihre Herausforderung entwickeln.
        Von dem Entwurf und der Umsetzung der Elektronik, über die Softwareentwicklung, bis zur Auswertung der Daten können Sie sich auf uns verlassen.
        Wir setzen in unserem Projektmanagement auf agile Arbeitsweisen.
        Dadurch sind Sie stets nah am Entwicklungsprozess, sodass wir gemeinsam flexibel auf Änderungen reagieren können.

        Erfahren Sie mehr zu [unserer technischen Expertise und Entwicklungsarbeit]( https://new.iotec-gmbh.de/exemplarische-entwicklung.html).

  - image: images/forschung.png
    title: Forschung
    description: |
        Wir haben den Anspruch immer die neuesten Erkenntnisse und Technologien in unsere Arbeit zu integrieren.
        Deshalb sind wir aktiver Forschungspartner in vielen industriellen Forschungsprojekten.
        In diesen Projekten arbeiten wir mit verschiedenen Hochschuleinrichtungen
        und Forschungsinstituten wie beispielsweise der [Hochschule Osnabrück](https://www.hs-osnabrueck.de/)
        und dem [Fraunhofer Institut](https://www.fraunhofer.de/) zusammen.
researchs:
  - name: soil2data – Mobiles Bodenproben-Labor und Datenfusion für den ressourceneffizienten Pflanzenbau
    id: soil2data
    partners:
      - name: Hochschule Osnabrück
        url: https://www.hs-osnabrueck.de
      - name: Anedo Ltd.
        url: https://anedo.eu
      - name: Bodenprobetechnik Nietfeld GmbH
        url: http://www.bodenprobetechnik.de
      - name: LUFA Nord West
        url: https://www.lufa-nord-west.de
      - name: MMM tech support GmbH & Co.KG
        url: https://www.mmm-tech.de
    owners: images/logo_ptble.jpg
    period: 2016-2020
  - name: OptiBlend – Smartphone basierte optische Verfahren zur Charakterisierung von Einzelkomponenten bei der Herstellung von mineralischen Mischdüngern und Ableitung von Streueigenschaften zur optimierten Streueinstellung bei Zentrifugalstreuern
    id: optiblend
    partners:
      - name: Hochschule Osnabrück
        url: https://www.hs-osnabrueck.de
      - name: Amazonen-Werke
        url: https://amazone.de
    owners: images/logo_ptble.jpg
    period: 2016-2020
  - name: DSSARTH – Entwicklung eines automatisierten Entscheidungshilfe Systems für den biologischen und integrierten Pflanzenschutz unter Glas
    id: dssarth
    partners:
      - name: Leibniz Universität Hannover
        url: https://www.uni-hannover.de
      - name: Katz Biotech AG
        url: https://www.katzbiotech.de
      - name: ISIP e.V.
        url: https://www.isip.de
    owners: images/logo_ptble.jpg
    period: 2017-2020
  - name: STEP-UP – Smarte Technologien für die normgerechte Prozessführung und Werker-Unterstützung in klebtechnischen Fertigungsprozessen
    id: stepup
    partners:
      - name: Fraunhofer-Institut für Fertigungstechnik und Angewandte Materialforschung
        url: https://www.ifam.fraunhofer.de
      - name: Bitnamic GmbH
        url: https://www.bitnamic.net
      - name: tec-n GmbH
        url: https://www.n-tec.de
      - name: OFFIS e.V.
        url: https://www.offis.de
    owners: images/BMBF_logo_deutsch.jpg
    period: 2019-2021
  - name: IPMaide – Sensorbasiertes Monitoring und Entscheidungshilfe für den integrierten Pflanzenschutz in Gewächshauskulturen
    id: ipmaide
    partners:
      - name: Leibniz Universität Hannover
        url: https://www.uni-hannover.de
      - name: Julius Kühn-Institut Institut
        url: https://www.julius-kuehn.de
      - name: Geoinformationsdienst GmbH
        url: https://www.geoinformationsdienst.de
    owners: images/logo_ptble.jpg
    period: 2019-2022
