# Welcome to Jekyll!
#

# Site settings
title: iotec GmbH
description: |
    Wir machen Sensoren intelligent
owner: iotec GmbH # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: info@iotec-gmbh.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://new.iotec-gmbh.de" # the base hostname & protocol for your site
social:
  email: info@iotec-gmbh.de
  phone: '+49541-343711-00'
  linkedin-square: https://linkedin.com/company/iotec-gmbh
  github: https://github.com/iotec-gmbh

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Exlude files and directories from the page
exclude:
  # Seems like Jekyll is trying to build what is inside this directory
  - vendor/
  # This is for internal usage only
  - HOWTO.md

about:
  description: |
    iotec ist Ihr Spezialist für individuelle Sensorlösungen. Diese Lösungen befähigen Sie zu belastbaren Analysen Ihrer Prozesse.
    iotec steht Ihnen als starker Partner bei der Transition zu einem digitaleren Unternehmen zur Seite.
    Wir beraten Sie gern und finden mit Ihnen zusammen eine passgenaue Lösung für Ihre Problemstellung.
    Mithilfe unseres Netzwerks aus Industriepartnern und Forschungseinrichtungen unterstützen wir Sie von Machbarkeiten, über Prototypen bis zur Serie.
    Von Temperatursensoren bis zur Integration von Bildverarbeitungssystemen - wir arbeiten immer an der besten digitalen Lösung für Sie.

    Mehr Automatisierung, mehr Digitalisierung, mehr Effizienz für Ihr Unternehmen. Das leistet iotec für Sie.
    In kurzen, transparenten Entwicklungsschritten, entwickeln wir für Sie maßgeschneiderte Sensorlösungen.

# References
# To add new references, just copy the image to the images and add a new entry
# in the list below.
references:
  - image: images/boge.svg
    url: https://www.boge-rubber-plastics.com
  - image: images/bayer.svg
    url: https://www.bayer.de
  - image: images/lemken.svg
    url: https://lemken.com
  - image: images/inoex.svg
    url: https://www.inoex.de
  - image: images/hs-osnabrueck.svg
    url: https://www.hs-osnabrueck.de
  - image: images/nietfeld.jpg
    url: http://www.bodenprobetechnik.de

# Services
# *image*: Image next to the text
# *title*: Title of the service
# *description*: Description of the service. Intepreted as Markdown.
services:
  - image: images/consulting.jpg
    title: Beratung
    description: |
        Sie fragen sich welche Messmöglichkeiten es für Ihre Prozesse gibt
        und wie man diese am besten in Ihre eigene Infrastruktur integriert?
        Wir beraten Sie gerne!

        Nachdem wir gemeinsam Ihre Situation analysiert haben,
        erarbeiten wir ein Konzept mit Ihnen.
        Durch unser interdisziplinäres Team und unser Netzwerk in Industrie und Forschung,
        haben sie dabei Zugriff auf eine breite Wissensbasis.
  - image: images/entwicklung.png
    title: Entwicklung
    description: |
        Ob die Elektronik für ihre Spezialanwendung oder das komplette Sensorsystem –
        wir entwickeln eine für Sie maßgeschneiderte Lösung.

        Sie profitieren dabei von unserem jungen und innovativen Team mit Expertise im Software- und im Hardwarebereich.

        Durch unser Projektmanagement sind Sie immer nah am Entwicklungsprozess und behalten so den vollen Überblick.
        Gemeinsam können wir schnell auf äußere Einflüsse oder neue Entwicklungen reagieren.
  - image: images/forschung.png
    title: Forschung
    description: |
        Wir haben den Anspruch immer die neuesten Erkenntnisse und Technologien in unsere Arbeit zu integrieren.
        Deshalb sind wir aktiver Forschungspartner in vielen industriellen Forschungsprojekten.
        Dabei werden wir von einem großen Netzwerk aus verschiedenen Hochschuleinrichtungen
        und Forschungsinstituten wie beispielsweise der [Hochschule Osnabrück](https://www.hs-osnabrueck.de/) und dem [Fraunhofer Institut](https://www.fraunhofer.de/) unterstützt.

researchs:
  - name: Soil2data
    partners:
      - name: Hochschule Osnabrück
        url: www.hs-osnabrueck.de
      - name: Anedo Ltd.
        url: anedo.eu
      - name: Bodenprobetechnik Nietfeld GmbH
        url: www.bodenprobetechnik.de
      - name: LUFA Nord West
        url: www.lufa-nord-west.de
      - name: MMM tech support GmbH & Co.KG
        url: www.mmm-tech.de
    owners: images/logo_ptble.jpg
    period: 2016-2019
  - name: OptiBlend
    partners:
      - name: Hochschule Osnabrück
        url: www.hs-osnabrueck.de
      - name: Amazonen-Werke
        url: amazone.de
    owners: images/logo_ptble.jpg
    period: 2016-2020
  - name: DSSARTH
    partners:
      - name: Leibniz Universität Hannover
        url: www.igps.uni-hannover.de
      - name: Katz Biotech AG
        url: www.katzbiotech.de
      - name: ISIP e.V.
        url: www.isip.de
    owners: images/logo_ptble.jpg
    period: 2017-2020
  - name: IPMaide
    partners:
      - name: Partner GmbH
        url: www.google.de
    owners: images/logo_ptble.jpg
    period: 2020-202?
  - name: S2D2
    partners:
      - name: Anedo Ltd.
        url: www.google.de
    owners: images/logo_ptble.jpg
    period: 2020-202?
  - name: AQM
    partners:
      - name: Anedo Ltd.
        url: www.google.de
    owners: images/logo_ptble.jpg
    period: 201?-201?
  - name: STEP-UP
    partners:
      - name: Anedo Ltd.
        url: www.google.de
    owners: images/logo_ptble.jpg
    period: 2019-202?
  - name: Nagerfalle
    partners:
      - name: Anedo Ltd.
        url: www.google.de
    owners: images/logo_ptble.jpg
    period: 201?-201?
